### ISSUE TITLE
Could we go on higher abstract level?

### ISSUE THREAD

**Issue by ipepe** [shibayan/JRubyExtension#3]
Could we go on higher abstract level and instead of calling puma directly, call `rack up`?

**Comment by shibayan** [comment]
Sorry, I'm not familiar with Ruby, tell me if there is a better way of writing.

**Comment by ipepe** [comment]
Yeah, rack is tool for starting http web apps in ruby lang. Usually if You have sintatra or rails app, You can simply write `bundle exec rackup` and app will start. It is good because Rack let's You abstract from what framework You start. I only have doubts about port env

**Comment by shibayan** [comment]
ok, I tried rackup. it very easily application startup.
https://github.com/shibayan/JRubyExtension/blob/master/content/Web.config#L7

**Comment by ipepe** [comment]
I have doubts if that is enough. I think that maybe `rack` should be installed like bundler. But I will have to google if that's a good practice.

**Comment by ipepe** [comment]
Anyway, thank You for changes. Are they available in SCM Extensions Gallery now?

**Comment by shibayan** [comment]
Yes, ship it
https://www.siteextensions.net/packages/jruby/
