### ISSUE TITLE
I tried installing but no success?

### ISSUE THREAD

**Issue by ipepe** [shibayan/JRubyExtension#4]
I clicked install on this extension for my website, but on installed extesion list it shows that website needs to be restarted for extension to work, and after restart it says the same.

But in debug console I get my jruby command so I guess it installed just fine... Theres only problem with detecting it being installed?

**Comment by shibayan** [comment]
Please try it from ARM Template. The installation will take a long time (5-6 min)
https://github.com/shibayan/azure-templates

**Comment by ipepe** [comment]
I'm not sure if I expressed myself right. On my debug console I have jruby available. I'm pointing to detection on: `website.scm.azurewebsites.net/SiteExtensions/#installed`, it seems funky...

**Comment by shibayan** [comment]
When you install from Azure Portal, an timeout error.
However, Web App inside is installing extension, after a few minutes to complete

**Comment by ipepe** [comment]
Its fine. You can close it.
